// User manual · English body. Mirrors content.zh.mjs one to one (build-manual.mjs checks section ids and figure numbers).
// Conventions: written for users; each module covers what it is / where to open it / how to use it / what to watch for.
// UI names follow the English strings in src/shared/i18n/dict/*.en.ts.
// Figures: number maps to site/assets/manual-en-<number>.webp (generated by scripts/manual-shots.mjs).
// Pin coordinates are percentages of the screenshot; English labels are wider, so this file keeps its own coordinates.

export const meta = {
  lang: 'en',
  title: 'User Manual · Eas-Term',
  description: 'The Eas-Term user manual: how to use the canvas, AI Chat, terminal, browser, version control, Code Map, References, Wiki, plugins, settings and more.',
  eyebrow: 'User Manual',
  heading: 'From first launch to everyday use, module by module',
  lede: 'This manual walks through the app one area at a time: what each part is, where to find it, how to use it and what to watch out for. Every screenshot is the real app running a demo project with made-up data. It reflects version 0.4.120; small details of the interface may change later.',
  toc: 'Contents',
  figLabel: 'Figure',
  tip: 'Tip',
  note: 'Note',
  keysHead: ['Action', 'macOS', 'Where']
}

export const sections = [
  { id: 'start', title: 'Quick start', body: `
<h3>System requirements</h3>
<ul>
<li><strong>macOS 12 or later</strong>, on both Apple silicon and Intel. On macOS 11, use version 0.4.113, which is still available on the <a href="download.html">download page</a>.</li>
<li><strong>Windows 10 or later (64-bit)</strong>. The installer isn't code-signed yet, so the first time you run it Windows may show a SmartScreen warning. Click "More info → Run anyway" to continue.</li>
</ul>
<h3>Install</h3>
<p>Download the installer for your system from the <a href="download.html">download page</a>. On macOS, open the dmg and drag Eas-Term into your Applications folder.</p>
<h3>First launch</h3>
<p>Eas-Term doesn't write code by itself. The work is done by AI command-line tools such as <strong>Claude Code</strong> and <strong>Codex</strong> (called CLIs in this manual), signed in with your own accounts. The first time you open the app, you'll see a setup screen:</p>
${'{{fig:01}}'}
<ul>
<li>CLIs that are already installed and signed in show "Logged in" right away.</li>
<li>For a CLI that isn't installed, click its button and a terminal opens to install it. Once it's installed, sign in once with your own account.</li>
<li>If you'd rather not use Claude Code or Codex, you can use <strong>omp</strong>, which ships with the app. It can sign in with subscriptions from several providers, or use an API key (stored in the Key Vault, see <a href="#vault">Key Vault</a>).</li>
<li>Click "Skip, I will do it myself" to go straight into the app. You can sign in any time later under "Settings › AI Chat".</li>
</ul>` },

  { id: 'overview', title: 'Interface overview', body: `
<p>The main window has a top bar and a workspace below it. Here's the canvas view:</p>
${'{{fig:02}}'}
<h3>Top bar</h3>
<ul>
<li><strong>Quota</strong>: keeps Claude, Codex and omp quota bars pinned to the top right of the canvas. Hover over one to see when it resets.</li>
<li><strong>References</strong>: a handbook of frontend and backend terms. See <a href="#refs">References</a>.</li>
<li><strong>Keys</strong>: opens the Key Vault. See <a href="#vault">Key Vault</a>.</li>
<li><strong>View switcher</strong>: switches between the four views (or use ⌘1–⌘4).</li>
<li><strong>Settings</strong>: also opens with ⌘,. See <a href="#settings">Settings</a>.</li>
<li>When tasks are queued or a tool call has been blocked, a reminder appears in the top bar; click it to jump to the relevant setting. When a new version is available, an update badge appears too.</li>
</ul>
<h3>Four views</h3>
<table class="mn-table"><tr><th>View</th><th>Best for</th><th>Shortcut</th></tr>
<tr><td><strong>Split</strong></td><td>A classic editor layout: projects and files on the left, tabs on the right that you can split side by side or top to bottom</td><td>⌘1</td></tr>
<tr><td><strong>Canvas</strong></td><td>An infinite canvas with one area (a Frame) per project. Terminals, AI chats, web pages, code and images all sit on it</td><td>⌘2</td></tr>
<tr><td><strong>Board</strong></td><td>One card per project, organized into "To do / In progress / Done"</td><td>⌘3</td></tr>
<tr><td><strong>Gantt</strong></td><td>Looking back at how long each AI turn took and which projects are moving</td><td>⌘4</td></tr></table>
<h3>Two drawers (canvas view)</h3>
<ul>
<li><strong>Left: "Files"</strong> (⌘B): projects, the file tree, components you can drag onto the canvas, and "done / awaiting approval" reminders.</li>
<li><strong>Right: "More"</strong> (⇧⌘B): four pages, Usage, Skills, Plugins and Wiki.</li>
</ul>
<p>The bottom right of the canvas holds the toolbar (select, rectangle, arrow, note, to-do, snapshot) and zoom controls. The minimap is in the bottom left.</p>` },

  { id: 'canvas', title: 'Canvas and Frames', body: `
<p>The canvas is where most of the work happens. Each project gets its own area with a title bar, called a <strong>Frame</strong>. The terminals, AI chats, web pages and files you open for a project live inside its Frame.</p>
<h3>Create a project Frame</h3>
<p><strong>Double-click</strong> an empty spot on the canvas to open the project menu. You can search, and sort by recently used or by date added; projects that are currently running are listed first. Pick one to create its Frame, or choose "Add Project Folder…" to add a new project.</p>
${'{{fig:03}}'}
<h3>Empty Frame: pick an AI to start</h3>
<p>A new Frame shows three buttons in the middle, <strong>Claude Code</strong>, <strong>Codex</strong> and <strong>omp</strong>, with "Open a terminal first" below them. If a CLI isn't installed, its button turns into "Install".</p>
${'{{fig:04}}'}
<h3>Add things to a Frame</h3>
<p><strong>Double-click</strong> inside a Frame to open the insert panel. Browse files by category (All, Chat, Docs, Media, 3D, Plugins…) and switch between "Folders" and "Recent". It remembers what you picked last time.</p>
${'{{fig:05}}'}
<h3>Frame context menu</h3>
${'{{fig:06}}'}
<ul>
<li><strong>New</strong>: AI Chat, Terminal, Browser.</li>
<li><strong>Components</strong>: Version Control, Design Module, Team Panel, Code Map, Plugin Panel (these need the Frame to be linked to a project).</li>
<li><strong>Plugins</strong>: opens the panel of any enabled plugin.</li>
<li>There's also Rename, Collapse / Expand, Move to board and Delete Frame.</li>
</ul>
<h3>Canvas tools and shortcuts</h3>
<ul>
<li><kbd>V</kbd> select, <kbd>R</kbd> rectangle, <kbd>A</kbd> arrow, <kbd>N</kbd> note, <kbd>T</kbd> to-do list. Hold <kbd>Space</kbd> and drag to pan.</li>
<li><kbd>⇧⌘O</kbd> tidies up into a grid, with terminals in the top left. <kbd>⌘=</kbd> / <kbd>⌘-</kbd> zoom, <kbd>⌘0</kbd> goes back to 100%, <kbd>⇧⌘0</kbd> fits everything. <kbd>F</kbd> focuses the selection, <kbd>⌘D</kbd> duplicates, <kbd>Delete</kbd> deletes.</li>
<li>Right-click an empty spot to add a note or a to-do list.</li>
</ul>
<h3>Maximize</h3>
<p>Every module has a maximize button in its top right corner, so it can fill the window while you focus. Press <kbd>Esc</kbd> to restore it. A maximized module always shows at 100%, regardless of the canvas zoom.</p>
<h3>Snapshot: send your markup to the AI</h3>
<p>The camera at the far right of the toolbar takes a snapshot. Drag over an area and it captures it together with the rectangles, arrows and notes you've drawn, ready to attach to an AI chat. Whether your markup is cleared afterwards is up to you, under "Settings › Board".</p>
<div class="mn-note"><strong>Up to 5 content modules</strong>: you can have at most 5 content modules (files, images, web pages and the like) open at once. Opening another closes the oldest one. To keep one, click the <strong>pin</strong> in its top right corner; pinned modules don't count toward the limit.</div>` },

  { id: 'chat', title: 'AI Chat', body: `
<p>The AI Chat module is where you talk to Claude Code, Codex or omp. Compared with running the CLI directly in a terminal, it adds approval cards, clickable options, images, a message queue and a checklist.</p>
${'{{fig:07}}'}
<h3>Start a chat</h3>
<p>Press <kbd>⌘J</kbd>, right-click a Frame and choose "New › AI Chat", or use the three buttons in an empty Frame. Before you start, you can choose:</p>
<ul>
<li><strong>Model and reasoning effort</strong>: click the model button at the bottom left of the input box, and set the effort with the slider.</li>
<li><strong>Codex sandbox</strong>: read-only, can edit the workspace, or full access.</li>
<li><strong>Role</strong>: under the input box, click "No role" to pick a role card. A role defines what the AI is responsible for and where its limits are (for example, no editing files or no running commands), and can have it work on a "Separate branch".</li>
</ul>
<h3>The input box</h3>
<ul>
<li><kbd>⌘Enter</kbd> sends, <kbd>Enter</kbd> adds a new line.</li>
<li>Type <kbd>@</kbd> to reference files, folders, skills, plugins, browser tabs, References terms and more. Each pick becomes a small chip.</li>
<li>Type <kbd>/</kbd> to run commands and skills.</li>
<li>Paste or drop images straight in, or attach the canvas snapshot you just took. The microphone on the right is <a href="#voice">voice input</a>.</li>
<li>Before sending, click the eye icon in the input box to preview exactly which text, images and references will go out.</li>
<li>When the AI's reply includes a suggestion, press <kbd>Tab</kbd> to put it in the input box (it fills in without sending). With the input box empty, press <kbd>↑</kbd> to bring back what you sent earlier in this session.</li>
</ul>
${'{{fig:09}}'}
<h3>Approvals</h3>
<p>When the AI wants to run a command, edit a file or call a tool, an approval card appears showing what it wants to do and in which folder. Click "Allow" or "Deny".</p>
${'{{fig:08}}'}
<p>To be interrupted less, go to "Settings › AI Chat": there's the "Ask first" switch, plus three approval levels for omp (Run directly / Approve all / Commands only).</p>
<h3>While the AI is busy</h3>
<ul>
<li>Messages you send go into a <strong>queue</strong>. You can cancel or reorder them, and they're sent automatically when the current turn ends.</li>
<li><strong>Redirect</strong> stops the current turn and sends your new message first. Use it to course-correct.</li>
<li>The stop button next to the input box stops the turn outright.</li>
</ul>
<h3>What you'll see in the chat</h3>
<ul>
<li><strong>Question navigation</strong> on the right lets you jump to any question you asked in a long chat. When you scroll away from the bottom, a "Latest" button takes you back.</li>
<li>Tool call logs are collapsed by default; click to see the details.</li>
<li>When the AI offers several options, they become cards you can click.</li>
<li>Images returned by the CLI are shown inline, can be enlarged and are saved locally.</li>
<li><strong>Checklist</strong>: for multi-step tasks, a checklist appears at the top of the chat and each step is ticked off as the AI finishes it. Expand it to see the details.</li>
<li><strong>Background tasks</strong>: commands the AI leaves running in the background (a dev server, for example) show "Running in background", with their own sound and a matching status on the Island.</li>
</ul>
<h3>History and compacting</h3>
<ul>
<li>"History" in the top right lists earlier chats for this module, this project or your pinned ones. You can search, preview and pick up where you left off.</li>
<li>When a chat gets long, you can <strong>Compact</strong> it manually (after confirming). The AI condenses the earlier conversation into a summary and carries on, which saves quota.</li>
</ul>
<h3>Coordination board</h3>
<p>When several AIs are working on different branches of the same project, they write their progress to the project's <code>.eas/board.md</code> (the coordination board). If another branch is editing the same file, the branch badge above the chat tells you to take a look first.</p>` },

  { id: 'terminal', title: 'Terminal', body: `
<p>A standard terminal. Press <kbd>⌘T</kbd> or right-click a Frame and choose "New › Terminal". The input box below it accepts pasted images and voice input. Hold <kbd>⌘</kbd> and click a path in the output to open the file. Right-click to add a to-do list that belongs to that terminal.</p>
${'{{fig:10}}'}
<div class="mn-tip">You can run <code>claude</code> or <code>codex</code> directly in the terminal too. The AI Chat module just adds approval cards, options, images and checklists on top.</div>` },

  { id: 'split', title: 'Split view', body: `
<p>Press ⌘1 for split view. The left sidebar has two pages, "Projects" and "Files / Version", and can collapse to a thin strip. The right side holds tabs: <kbd>⌘D</kbd> splits right, <kbd>⇧⌘D</kbd> splits down, and <kbd>⇧⌘]</kbd> / <kbd>⇧⌘[</kbd> switch tabs.</p>
${'{{fig:25}}'}
<p>The dropdown in the top left of each pane switches it to another type: Terminal, AI Chat, file preview, History, Wiki, Code Map, References and more.</p>` },

  { id: 'files', title: 'Files and previews', body: `
<p>Files you open from the file tree, the insert panel or an AI reply show up on the canvas as preview modules:</p>
<ul>
<li><strong>Code</strong>: syntax highlighted; click "Edit" in the bottom right to change it in place. <strong>Markdown</strong> is rendered, with a copy button on code blocks. <strong>Diffs</strong> show what changed.</li>
<li><strong>HTML</strong>: choose "Preview as Code" or "Preview as Web Page".</li>
<li><strong>Images</strong>: double-click to zoom, drag to pan, and use the grid to browse other images in the same folder.</li>
<li><strong>Video</strong>: pauses automatically when you click elsewhere, and can go full screen. <strong>Audio</strong> plays directly.</li>
<li><strong>3D</strong>: only .glb files can be previewed for now (the viewer, about 1 MB, downloads the first time).</li>
</ul>
${'{{fig:11}}'}
${'{{fig:14}}'}` },

  { id: 'browser', title: 'Browser', body: `
<p>Right-click a Frame and choose "New › Browser". It keeps you signed in to sites, and third-party sign-ins such as Google happen in a separate small window.</p>
${'{{fig:12}}'}
<ul>
<li><strong>Favorites bar</strong>: five fixed groups (motion, design, office, server sites and social media platforms), plus your own folders and stickers.</li>
<li><strong>Page zoom</strong>: when the browser is maximized, "− zoom +" to the right of the address bar scales only the web page, not the canvas.</li>
<li><strong>Page Viewer</strong>: when the AI is building a web page for you, put your local dev address (localhost) in the Page Viewer and watch changes as they happen. Reports the AI submits can sit above or below the page you're debugging.</li>
</ul>` },

  { id: 'git', title: 'Version Control (Git)', body: `
<p>Open the "Version" page in the split view sidebar, or the "Version Control" component on the canvas.</p>
${'{{fig:13}}'}
<ul>
<li>Stage, commit and discard changes. "AI summary" writes the description of your changes for you.</li>
<li>A branch graph and commit history; scroll down to load older commits. Tagged commits are marked.</li>
<li>Right-click a commit to check it out, create a branch from it, compare, add a tag, copy its hash or message, or reset to that version.</li>
</ul>
<div class="mn-note">"Discard" and "Reset" change the files in your working tree. The app asks you to confirm first; if you're unsure, make a commit before you do either.</div>` },

  { id: 'codemap', title: 'Code Map', body: `
<p>Right-click a Frame and choose "Components › Code Map". It draws your project as a graph so you can see which modules depend on which.</p>
${'{{fig:15}}'}
<ul>
<li><strong>Modules</strong> view: dependencies between files and folders, in a Ring or Cluster layout. Runtime circular dependencies are highlighted separately; those are the ones most worth fixing.</li>
<li><strong>Symbols</strong> view: which functions call which, and code nobody uses.</li>
<li>Supports JS/TS, Python (you need to install pyright yourself), C/C++ and Swift. Click a file name to open its code in the same Frame.</li>
</ul>` },

  { id: 'refs', title: 'References', body: `
<p>Open it with "References" in the top bar. It's a handbook of terms for people who build products: when you know the effect you want but not what it's called or how to ask the AI for it, look here.</p>
${'{{fig:22}}'}
<ul>
<li><strong>Terms</strong>: hundreds of frontend and backend techniques (debounce, skeleton screens, frosted glass, parallax…), grouped by scenario and searchable. Hover over one to see an animated example and an explanation.</li>
<li><strong>Click a term</strong> to attach it to the AI input box as a small chip. When you send, it expands into a complete, ready-to-run prompt.</li>
<li><strong>Blueprints</strong>: the sections that common pages (home page, detail page, settings page…) are made of. Click a section to jump to the matching terms.</li>
<li><strong>Design picker</strong>: filter and preview hundreds of design systems by interface type, then attach one's color palette or full spec to your chat.</li>
</ul>` },

  { id: 'drawers', title: 'Side drawers', body: `
<p>Each side of the canvas has a drawer.</p>
<h3>Left: Files (⌘B)</h3>
${'{{fig:17}}'}
<p>The project list, the current project's file tree, and components you can drag onto the canvas. When an AI finishes a task or is waiting for your approval, a reminder bubble appears here too.</p>
<h3>Right: More (⇧⌘B)</h3>
<p>Four pages: <a href="#usage">Usage</a>, <a href="#skills">Skills</a>, <a href="#plugins">Plugins</a> and <a href="#wiki">Wiki</a>, each covered in the sections below.</p>` },

  { id: 'wiki', title: 'Wiki', body: `
<p>"More › Wiki". Your wiki is simply a folder of markdown files you choose, where both you and the AI keep notes.</p>
${'{{fig:18}}'}
<ul>
<li>The first time, pick a folder to use as your wiki.</li>
<li>New material lands in the <strong>Inbox</strong> first. Ask the AI for an <strong>Archive plan</strong>; it only acts after you've checked and confirmed each item. If the wiki is a git repository, a snapshot is taken first, so you can roll back an archive you don't like.</li>
<li>Three tabs: Files, Graph (how notes link to each other) and Health (broken links, orphan pages, missing summaries and so on). Backlinks are supported.</li>
<li>Audio and video can be transcribed to text locally and saved in.</li>
</ul>` },

  { id: 'plugins', title: 'Plugins and the Plugin Market', body: `
<p>"More › Plugins". Plugins give you and the AI ready-made abilities, such as reading and writing Word, Excel and PowerPoint files, checking the weather, querying Amap, or connecting to Notion and GitHub.</p>
${'{{fig:19}}'}
<ul>
<li>Installed plugins have an on/off switch. <strong>Only plugins that are switched on</strong> appear in the double-click insert panel and in @ references, and only those can be used by the AI.</li>
<li>Click "Install" for one you don't have yet. "Full Plugin Market" lets you browse by category, search and check for updates, and add other plugin sources (they must be public HTTPS addresses).</li>
<li>Bundled with the app: Board (a three-column to-do board per project), Publish Desk (write content per platform and check for banned words), Timeline (project milestones recorded by the AI, plus weekly report receipts) and Jev (requires setting up an external service yourself).</li>
<li>The switches for the system plugins "Checklist" and "Computer View" are in "Settings › MCP Access › Built-in plugins". Computer View can take screenshots for the AI to look at, with sensitive windows blurred. To let it click or type, you must grant time-limited permission separately in its panel, and give Eas-Term the macOS "Accessibility" permission.</li>
<li>Plugins that need a key keep it in the <a href="#vault">Key Vault</a>, so it never shows up in a chat.</li>
</ul>` },

  { id: 'skills', title: 'Skills', body: `
<p>"More › Skills". Lists the skills each CLI on your machine can use, grouped by CLI / project / global, with search.</p>
${'{{fig:20}}'}
<ul>
<li>Add your own folders and drag skills into categories.</li>
<li>Disable any skill individually (this only applies inside Eas-Term and doesn't touch your files).</li>
<li>The "AI discovery" switch: turn it off and the AI won't pick skills on its own; a skill is only used when you call it with a / command or by name. Handy when you have lots of skills and the AI keeps reaching for the wrong ones.</li>
</ul>` },

  { id: 'usage', title: 'Usage and quota', body: `
<p>"More › Usage" shows how much you've used:</p>
${'{{fig:21}}'}
<ul>
<li>Token usage by project, session and individual request, for today, the last 7 days or the last 30 days.</li>
<li>A 90-day heatmap that switches between "Token" and "App activity".</li>
<li>Weekly and monthly report receipts you can copy or save as an image.</li>
</ul>
<p>The "Quota" switch in the top bar keeps quota bars for all three CLIs in the top right of the canvas; hover over them to see when they reset. Claude's percentages require turning on quota reading in "Settings › AI Chat".</p>` },

  { id: 'board', title: 'Board', body: `
<p>Press ⌘3 for the board. Each project gets one card showing how many terminals and AI chats it has, and which are running or waiting for you.</p>
${'{{fig:23}}'}
<ul>
<li>Drag cards to change their status; dragging to the edge scrolls automatically.</li>
<li>Columns can be added, renamed and deleted (delete a column and its projects go back to "Uncategorized").</li>
<li>On the canvas, right-click a Frame and choose "Move to board" to change its status too.</li>
</ul>` },

  { id: 'gantt', title: 'Gantt', body: `
<p>Press ⌘4 for the Gantt view, which shows how long each AI turn took, from the moment you sent a message to when the AI finished.</p>
${'{{fig:24}}'}
<ul>
<li>Three ways to look at it: <strong>Sessions</strong>, <strong>Projects</strong> and <strong>Milestones</strong> (one diamond per commit, a bigger one for tagged commits).</li>
<li>Switch between "24 hours" and "3 days", hold <kbd>⌃</kbd> and scroll to zoom, and use the week strip at the bottom to jump to a date.</li>
<li>Right-click a bar to jump to that terminal in the split view, canvas or board. You can also delete a single bar or clear them all.</li>
<li>Only data from after you installed this version is recorded, so it starts out empty.</li>
</ul>` },

  { id: 'team', title: 'Teams and multi-agent', body: `
<p>Have several AIs split up the work and run at the same time. This is off by default: turn on the <strong>multi-agent switch</strong> in the Frame title bar before the AI can form a team, and you'll still be asked to confirm before it does.</p>
${'{{fig:16}}'}
<ul>
<li>Right-click a Frame and choose "Components › Team Panel" to see the status and usage of every AI session in the project. Stop them one at a time or all at once.</li>
<li>A session only appears in the panel after it has sent its first message and its CLI is running.</li>
<li>Each AI can work on its own separate branch, and they record their progress on the coordination board.</li>
</ul>` },

  { id: 'vault', title: 'Key Vault', body: `
<p>"Keys" in the top bar. API keys, tokens and other secrets belong here. <strong>Don't paste them into a chat.</strong></p>
${'{{fig:26}}'}
<ul>
<li>The first time, set a 6-digit code. You can check "Trust this device" to unlock automatically from then on.</li>
<li>When an AI or plugin needs a key, a dialog shows which project, which module and which key it's asking for. It only gets the key after you approve.</li>
<li>Keys are injected only into the running program and never appear in the chat.</li>
</ul>` },

  { id: 'island', title: 'Island', body: `
<p>A small pill at the top of your screen that tells you what's happening in Eas-Term while you're in another app: how many projects are running, which AI has finished, and which is waiting for your approval.</p>
${'{{fig:34}}'}
<ul>
<li>It steps aside when Eas-Term is in the foreground, so it never gets in your way.</li>
<li>Right-click to shrink it to a small dot. If you don't want it, turn it off in "Settings › Appearance"; to bring it back, right-click the Dock icon and choose "Show Island".</li>
</ul>` },

  { id: 'voice', title: 'Voice input', body: `
<p>The input boxes for AI Chat and the terminal both have a microphone on the right. Speech is recognized offline on your computer and no audio is uploaded. The recognition model downloads the first time you use it.</p>
<ul>
<li>Three modes: Standard (filters out everything except voices), Strong (for noisy places, may miss quiet speech) and Basic (uses only your device's own noise reduction).</li>
<li>When you finish speaking, release or click again. The recognized text goes into the input box and is not sent automatically.</li>
</ul>` },

  { id: 'phone', title: 'Phone', body: `
<p>"Settings › Phone". Follow the projects and AI progress on this computer from your phone.</p>
${'{{fig:30}}'}
<ul>
<li>Turn on the switch and your computer opens a port on the local network and shows a QR code. Scan it with your phone, then click "Allow" on the computer to finish pairing.</li>
<li>For now, your phone and computer need to be on the <strong>same Wi-Fi</strong>.</li>
<li>You can remove paired devices at any time, and actions taken from the phone are logged. Turn the switch off when you're done and the port closes immediately.</li>
</ul>` },

  { id: 'settings', title: 'Settings', body: `
<p>Open with <kbd>⌘,</kbd>. The left side has three groups, with a search box at the top.</p>
${'{{fig:27}}'}
<h3>Workspace</h3>
<ul>
<li><strong>Appearance</strong>: theme (Dark / Light / System), <strong>Interface language</strong> (Chinese / English / Follow System; changes apply immediately and the AI replies in the matching language), and the Island switch.</li>
<li><strong>Board</strong>: whether to clear your markup after a snapshot.</li>
<li><strong>Sounds &amp; Alerts</strong>: three sounds, for done, awaiting approval and running in background.</li>
<li><strong>Shortcuts</strong>: change any shortcut, or restore the defaults.</li>
</ul>
${'{{fig:33}}'}
<h3>AI &amp; Connections</h3>
<ul>
<li><strong>AI Chat</strong>: sign in to Claude Code and Codex, "Ask first", the three omp approval levels, and quota reading.</li>
<li><strong>MCP Access</strong>: a log of the Eas-Term tools the AI has called, plus switches for the core connections (Workbench, Bizone Canvas, Usage guide) and the built-in plugins.</li>
<li><strong>Phone</strong>: see the previous section.</li>
</ul>
${'{{fig:28}}'}
${'{{fig:29}}'}
<h3>System</h3>
<ul>
<li><strong>Updates</strong>: checks for new versions of Eas-Term (it only downloads and opens the installer, never installs on its own). Automatic updates for Claude Code and Codex are off by default; you can turn them on, and roll back too.</li>
<li><strong>Runtime &amp; Resources</strong> and <strong>Performance &amp; Diagnostics</strong>: how many tasks run at once, graphics status, and troubleshooting logs.</li>
<li><strong>Privacy &amp; Extensions</strong>: anonymous usage statistics (on by default, can be turned off), and a list of everything Eas-Term has written to your computer, each of which can be removed. See <a href="privacy.html">Privacy &amp; Data</a>.</li>
<li><strong>About &amp; Open Source</strong>.</li>
</ul>
${'{{fig:31}}'}
${'{{fig:32}}'}` },

  { id: 'keys', title: 'Keyboard shortcuts', body: `
<p>The most common shortcuts are listed below (on Windows, replace ⌘ with Ctrl). You can change all of them in "Settings › Shortcuts".</p>
{{keys}}` },

  { id: 'faq', title: 'FAQ', body: `
<h3>AI Chat says "Needs login"</h3>
<p>The CLI it uses isn't signed in yet. Click "Log in and continue" to open a terminal and sign in with your own account, or click "Switch to Codex" (or another option) to use a different one.</p>
<h3>I clicked Claude Code or Codex and the button turned into "Install"</h3>
<p>That CLI isn't installed on this computer yet. Click "Install" to open a terminal that runs the install command. If your network is restricted, you can use omp, which ships with the app, instead.</p>
<h3>Files or web pages I opened close on their own after a while</h3>
<p>You can have at most 5 content modules open at once; opening more closes the oldest. Click the pin in a module's top right corner to keep it.</p>
<h3>The AI keeps stopping to wait for my approval</h3>
<p>Turn off "Ask first" in "Settings › AI Chat", or set omp's approval level to "Run directly" or "Commands only".</p>
<h3>How do I switch between Chinese and English?</h3>
<p>"Settings › Appearance › Interface language". It follows your system by default; if you upgraded from an older version, it stays in Chinese.</p>
<h3>Is my data uploaded?</h3>
<p>Your project files and chat content are never uploaded to Eas-Term. Anonymous usage statistics only include usage time and feature counts, and you can turn them off in Settings. See <a href="privacy.html">Privacy &amp; Data</a> for the full details.</p>
<h3>Still have questions?</h3>
<p>Check the <a href="changelog.html">changelog</a> to see what's changed recently.</p>` }
]

export const figs = {
  '01': { cap: 'First launch: sign in to an AI, or skip for now' },
  '02': { cap: 'The main window in canvas view', pins: [
    { n: 1, x: 77.4, y: 5.6, t: 'Quota' }, { n: 2, x: 82.2, y: 5.6, t: 'References' }, { n: 3, x: 86.7, y: 5.6, t: 'Keys' },
    { n: 4, x: 91.4, y: 5.6, t: 'View switcher' }, { n: 5, x: 96.9, y: 5.6, t: 'Settings' }, { n: 6, x: 11.8, y: 7.2, t: 'Frame title bar' },
    { n: 7, x: 4.2, y: 51.7, t: 'Left drawer: Files' }, { n: 8, x: 95.8, y: 51.8, t: 'Right drawer: More' }, { n: 9, x: 81, y: 92.4, t: 'Canvas toolbar' },
    { n: 10, x: 93.8, y: 92.4, t: 'Zoom' }, { n: 11, x: 5.2, y: 96.7, t: 'Minimap' } ] },
  '03': { cap: 'Double-click an empty spot: pick a project to create its Frame' },
  '04': { cap: 'Empty Frame: pick an AI to start, or open a terminal first' },
  '05': { cap: 'Double-click inside a Frame: the insert panel' },
  '06': { cap: 'Frame context menu' },
  '07': { cap: 'AI Chat: activity log, checklist and reply' },
  '08': { cap: 'Approval card: Allow or Deny' },
  '09': { cap: 'Type @ to reference files, skills, References terms and more' },
  '10': { cap: 'Terminal' },
  '11': { cap: 'Code preview' },
  '12': { cap: 'Browser and favorites bar' },
  '13': { cap: 'Version Control: branch graph and commits' },
  '14': { cap: 'Image preview' },
  '15': { cap: 'Code Map' },
  '16': { cap: 'Team Panel (before any sessions exist)' },
  '17': { cap: 'Left drawer: Files' },
  '18': { cap: 'More › Wiki' },
  '19': { cap: 'More › Plugins' },
  '20': { cap: 'More › Skills' },
  '21': { cap: 'More › Usage' },
  '22': { cap: 'References: hover over a term to see an example' },
  '23': { cap: 'Board' },
  '24': { cap: 'Gantt' },
  '25': { cap: 'Split view: AI Chat on the left, file preview on the right' },
  '26': { cap: 'Opening the Key Vault for the first time: set a 6-digit code' },
  '27': { cap: 'Settings › Appearance (including Interface language)' },
  '28': { cap: 'Settings › AI Chat' },
  '29': { cap: 'Settings › MCP Access' },
  '30': { cap: 'Settings › Phone' },
  '31': { cap: 'Settings › Updates' },
  '32': { cap: 'Settings › Privacy & Extensions' },
  '33': { cap: 'Settings › Shortcuts' },
  '34': { cap: 'Island' }
}

export const keys = [
  ['Open settings', '⌘,', ''], ['New terminal', '⌘T', ''], ['New AI chat', '⌘J', ''], ['Close current pane', '⌘W', 'Split view'],
  ['Split right / Split down', '⌘D / ⇧⌘D', 'Split view'], ['Next tab / Previous tab', '⇧⌘] / ⇧⌘[', 'Split view'],
  ['Switch to Split / Canvas / Board / Gantt', '⌘1 / ⌘2 / ⌘3 / ⌘4', ''],
  ['Left drawer / Right drawer', '⌘B / ⇧⌘B', 'Canvas'], ['Tidy up', '⇧⌘O', 'Canvas'], ['Zoom in / Zoom out / 100% / Fit all', '⌘= / ⌘- / ⌘0 / ⇧⌘0', 'Canvas'],
  ['Select / Rectangle / Arrow / Note / To-do', 'V / R / A / N / T', 'Canvas'], ['Focus selection', 'F', 'Canvas'], ['Pan', 'Hold Space and drag', 'Canvas'],
  ['Send message', '⌘Enter', 'AI Chat'], ['Exit maximize / Close popup', 'Esc', '']
]
