import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {capture,candidates,resolveCandidate,attachJevSuggestion} from './candidates.mjs';import {list,get} from './store.mjs';
test('candidate replay deduplicates; confirm persists pending milestone; ignore does not inflate heatmap',t=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'candidates-'));t.after(()=>fs.rmSync(cwd,{recursive:true,force:true}));const e={eventId:'e',sessionId:'s',turnId:'t',projectId:'p',date:'2026-09-18',completedAt:'2026-09-18T15:00:00Z',outcome:'completed',text:'已完成候选记录',originalQuestion:'请修复候选记录'};const r=capture(cwd,e);assert.equal(capture(cwd,e).captured,false);assert.equal(list(cwd).total,0);assert.equal(candidates(cwd).length,1);resolveCandidate(cwd,r.id,'confirm');assert.equal(list(cwd).total,1);assert.equal(get(cwd,list(cwd).items[0].id).originalQuestion,'请修复候选记录');assert.equal(candidates(cwd).length,0);assert.equal(resolveCandidate(cwd,r.id,'confirm').changed,false);const r2=capture(cwd,{...e,eventId:'e2'});resolveCandidate(cwd,r2.id,'ignore');assert.equal(list(cwd).total,1)})
test('corrupt candidate file and symlink are rejected without overwriting',t=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'candidates-safe-'));t.after(()=>fs.rmSync(cwd,{recursive:true,force:true}));fs.mkdirSync(path.join(cwd,'.eas'));const file=path.join(cwd,'.eas/timeline-candidates.json');fs.writeFileSync(file,'broken');assert.throws(()=>candidates(cwd));assert.equal(fs.readFileSync(file,'utf8'),'broken');fs.unlinkSync(file);const target=path.join(cwd,'unrelated');fs.writeFileSync(target,'keep');fs.symlinkSync(target,file);assert.throws(()=>candidates(cwd),/软链/);assert.equal(fs.readFileSync(target,'utf8'),'keep')})
test('failed confirmation retains candidate and can be retried after store repaired',t=>{const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'candidates-retry-'));t.after(()=>fs.rmSync(cwd,{recursive:true,force:true}));const e={eventId:'e',sessionId:'s',turnId:'t',projectId:'p',date:'2026-09-18',completedAt:'2026-09-18T15:00:00Z',outcome:'completed',text:'已完成重试验证'};const r=capture(cwd,e),file=path.join(cwd,'.eas/timeline.json');fs.writeFileSync(file,'broken');assert.throws(()=>resolveCandidate(cwd,r.id,'confirm'));assert.equal(candidates(cwd).length,1);assert.equal(fs.readFileSync(file,'utf8'),'broken');fs.unlinkSync(file);resolveCandidate(cwd,r.id,'confirm');assert.equal(candidates(cwd).length,0);assert.equal(list(cwd).total,1)})

test('Jev enrichment never confirms a candidate or changes heatmap; late results ignored',t=>{
 const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'candidates-jev-'));t.after(()=>fs.rmSync(cwd,{recursive:true,force:true}))
 const event={eventId:'e',sessionId:'s',turnId:'t',projectId:'p',date:'2026-09-18',completedAt:'2026-09-18T15:00:00Z',outcome:'completed',text:'已完成图片修复'}
 const {id}=capture(cwd,event),advice={candidateId:id,requiresReview:true,milestone:{probability:.8,accepted:false},project:{projectId:'p',confidence:.7},secret:'not persisted'}
 assert.equal(attachJevSuggestion(cwd,id,advice).changed,true)
 assert.equal(candidates(cwd)[0].review,'pending');assert.equal(list(cwd).total,0)
 assert.equal(JSON.stringify(candidates(cwd)).includes('not persisted'),false)
 assert.throws(()=>attachJevSuggestion(cwd,id,{...advice,milestone:{probability:.8,accepted:true}}))
 resolveCandidate(cwd,id,'ignore');assert.equal(attachJevSuggestion(cwd,id,advice).changed,false)
})
