import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createSaveBarrier} from './saveBarrier.ts'
test('failure retains dirty data and retry requires another flush',async()=>{let ok=false,calls=0;const p=createSaveBarrier(()=>1,async()=>{calls++;return ok});p.markDirty();assert.equal(await p.flush(),false);assert.equal(p.isDirty(),true);assert.equal(calls,1);ok=true;assert.equal(await p.flush(),true);assert.equal(p.isDirty(),false)})
test('rejection is converted to failed acknowledgement, not unhandled rejection',async()=>{const p=createSaveBarrier(()=>1,async()=>{throw Error('disk')});p.markDirty();assert.equal(await p.flush(),false);assert.equal(p.isDirty(),true)})
test('concurrent flush coalesces and new edit is saved before success',async()=>{let value=1;const writes:number[]=[];let release!:()=>void;const p=createSaveBarrier(()=>value,async v=>{writes.push(v);if(v===1)await new Promise<void>(r=>release=r);return true});p.markDirty();const a=p.flush(),b=p.flush();assert.equal(a,b);await Promise.resolve();value=2;p.markDirty();release();assert.equal(await a,true);assert.deepEqual(writes,[1,2]);assert.equal(p.isDirty(),false)})
test('snapshot failure remains dirty',async()=>{const p=createSaveBarrier(()=>{throw Error('serialize')},async()=>true);p.markDirty();assert.equal(await p.flush(),false);assert.equal(p.isDirty(),true)})
test('sync failure remains dirty; success consumes current revision',()=>{const p=createSaveBarrier(()=>3,async()=>true);p.markDirty();assert.equal(p.flushSync(()=>false),false);assert.equal(p.isDirty(),true);assert.equal(p.flushSync(()=>true),true);assert.equal(p.isDirty(),false)})
test('old async ACK cannot undo a newer sync acknowledgement',async()=>{let value=1,done!:(ok:boolean)=>void;const writes:number[]=[];const p=createSaveBarrier(()=>value,async v=>{writes.push(v);return new Promise<boolean>(r=>done=r)});p.markDirty();const pending=p.flush();await Promise.resolve();value=2;p.markDirty();assert.equal(p.flushSync(v=>{writes.push(v);return true}),true);done(true);assert.equal(await pending,true);assert.equal(p.isDirty(),false);assert.deepEqual(writes,[1,2])})
test('new edit during a failed save is retained for retry',async()=>{let value=1,done!:(ok:boolean)=>void,first=true;const writes:number[]=[];const p=createSaveBarrier(()=>value,async v=>{writes.push(v);if(first){first=false;return new Promise<boolean>(r=>done=r)}return true});p.markDirty();const pending=p.flush();await Promise.resolve();value=2;p.markDirty();done(false);assert.equal(await pending,false);assert.equal(p.isDirty(),true);assert.equal(await p.flush(),true);assert.deepEqual(writes,[1,2]);assert.equal(p.isDirty(),false)})
