import {useEffect,useRef,useState} from 'react'
import {STICKERS,type Favorites,type FavoriteChange} from '../../../../shared/browserFavorites'
import './favorites.css'
type Capture={name:string;url:string;guestId?:number}
export function FavoritesPanel({folder,onFolder,onOpen,bookmark,onCloseBookmark,visible,active}:{folder:string;onFolder:(id:string)=>void;onOpen:(url:string)=>void;bookmark:Capture|null;onCloseBookmark:()=>void;visible:boolean;active:boolean}):JSX.Element{
 const [data,setData]=useState<Favorites|null>(null),[error,E]=useState(''),[busy,B]=useState(false),[notice,N]=useState(''),[lastFolder,L]=useState('')
 const [name,SN]=useState(''),[url,SU]=useState(''),[dest,SD]=useState(''),[capture,SC]=useState(false)
 const [edit,SE]=useState<{id?:string;name:string;sticker:string}|null>(null),[query,SQ]=useState(''),[more,SM]=useState(false),[paused,SP]=useState(false)
 const folderTimer=useRef<ReturnType<typeof setTimeout>>()
 useEffect(()=>()=>clearTimeout(folderTimer.current),[])
 const row=useRef<HTMLDivElement>(null),host=useRef<HTMLDivElement>(null),drag=useRef<{x:number;left:number;moved:boolean}|null>(null),moved=useRef(false)
 useEffect(()=>{void window.api.browser.favorites().then(setData).catch(e=>E(String(e)));return window.api.browser.onFavorites(setData)},[])
 useEffect(()=>{if(bookmark){SN(bookmark.name);SU(bookmark.url);SD(folder||'media');SC(false);E('')}},[bookmark,folder])
 useEffect(()=>{const el=row.current;if(!el)return;const sync=():void=>SM(el.scrollWidth-el.clientWidth-el.scrollLeft>4);sync();const ro=new ResizeObserver(sync);ro.observe(el);el.addEventListener('scroll',sync,{passive:true});const wheel=(e:WheelEvent):void=>{if(e.ctrlKey||Math.abs(e.deltaX)>=Math.abs(e.deltaY))return;const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?el.clientWidth:1);const end=el.scrollWidth-el.clientWidth;if((delta>0&&el.scrollLeft<end-1)||(delta<0&&el.scrollLeft>1)){e.preventDefault();e.stopPropagation();el.scrollLeft+=delta}};el.addEventListener('wheel',wheel,{passive:false});return()=>{ro.disconnect();el.removeEventListener('scroll',sync);el.removeEventListener('wheel',wheel)}},[data,folder,query,visible])
 useEffect(()=>{if(!host.current)return;let intersecting=true;const sync=():void=>SP(!intersecting||document.hidden||!visible||!active);const io=new IntersectionObserver(e=>{intersecting=e[0].isIntersecting;sync()});io.observe(host.current);document.addEventListener('visibilitychange',sync);sync();return()=>{io.disconnect();document.removeEventListener('visibilitychange',sync)}},[visible,active])
 useEffect(()=>{if(!bookmark&&!edit&&lastFolder!=='manual')return;const close=(e:KeyboardEvent):void=>{if(e.key==='Escape'){if(edit)SE(null);else {onCloseBookmark();L('')}}if(e.key==='Tab'){const dialog=host.current?.querySelectorAll<HTMLElement>('[role=dialog]');const items=dialog?.[dialog.length-1]?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select');if(items?.length){const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[bookmark,edit,lastFolder,onCloseBookmark])
 const change=async(op:FavoriteChange):Promise<boolean>=>{B(true);E('');try{const res=await window.api.browser.change(op);setData(res.data);N(op.type==='save'?(res.warning||'已收藏'):'');return true}catch(e){E(String(e).replace(/^Error:.*?: /,''));return false}finally{B(false)}}
 const current=data?.folders.find(f=>f.id===folder)
 const sites=data?.sites.filter(s=>(!folder||s.folderId===folder)&&(!query||(s.name+s.description+(s.url||'')).toLowerCase().includes(query.toLowerCase())))||[]
 const colors=['#ad8cff','#f75b30','#73a9ac','#c6f477','#b5b5c1','#edbacb']
 return <div className={'favorites-root'+(paused?' is-paused':'')} ref={host}>
 <nav className="favorites-nav"><button onClick={()=>onFolder('')}>☆ 全部收藏</button>{data?.folders.map(f=><button key={f.id} className={folder===f.id?'active':''} onClick={()=>onFolder(f.id)}>{f.sticker} {f.name}</button>)}</nav>
 {visible&&<><div className="favorites-content"><header><div><button className="favorites-back" onClick={()=>onFolder('')}>收藏夹{current?' / '+current.name:''}</button><h2>{current?.name||'你的常用网站，井然有序。'}</h2></div><input aria-label="搜索收藏" placeholder="搜索收藏的网站…" value={query} onChange={e=>SQ(e.target.value)}/></header>
 {!folder&&!query&&<div className="favorite-folders">{data?.folders.map((f,i)=><button key={f.id} className="favorite-folder" onClick={e=>{const b=e.currentTarget;b.classList.add('entering');clearTimeout(folderTimer.current);folderTimer.current=setTimeout(()=>{onFolder(f.id);b.classList.remove('entering')},matchMedia('(prefers-reduced-motion: reduce)').matches?0:220)}} onContextMenu={e=>{e.preventDefault();SE({...f})}}>
 <span className="favorite-folder-art"><span className="favorite-back"/><span className="favorite-sheet one">↗</span><span className="favorite-sheet two">{data.sites.find(s=>s.folderId===f.id)?.name.slice(0,2)||'＋'}</span><span className="favorite-sheet three">✦</span><span className="favorite-front"><i>{f.sticker}</i><i style={{color:colors[i%colors.length]}}>✦</i></span></span><strong>{f.name}</strong><small>{data.sites.filter(s=>s.folderId===f.id).length} 个网站 · {f.builtin?'固定':'自定义'}</small></button>)}<button className="favorite-new" onClick={()=>SE({name:'',sticker:'✦'})}>＋ 新建文件夹</button></div>}
 {(folder||query)&&<><div className="favorite-count">{sites.length} 个网站 <button onClick={()=>{SN('');SU('');SD(folder||'media');SC(false);L('manual')}}>＋ 收藏网站</button></div><div className="favorite-strip"><div className="favorite-row" ref={row}
 onPointerDown={e=>{if(e.button!==0||e.pointerType==='touch'||(e.target as HTMLElement).closest('.favorite-site-actions'))return;drag.current={x:e.clientX,left:e.currentTarget.scrollLeft,moved:false};moved.current=false}}
 onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x;if(Math.abs(dx)>6){d.moved=true;moved.current=true;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.scrollLeft=d.left-dx}}}
 onPointerUp={()=>{drag.current=null;setTimeout(()=>{moved.current=false},0)}} onPointerCancel={()=>{drag.current=null;moved.current=false}}
 onClickCapture={e=>{if(moved.current){e.stopPropagation();e.preventDefault()}}}>
 {sites.map((s,i)=><article key={s.id} className="favorite-site" style={{background:colors[i%colors.length]}}><button className="favorite-site-open" disabled={!s.url} onClick={()=>s.url&&onOpen(s.url)}>
 <div className="favorite-preview"><span>{['◯','⌁','✦','↗','⌘'][i%5]}</span>{s.preview?<img src={s.preview} alt={s.name+'的本机预览'} draggable={false} loading="lazy" onError={e=>{e.currentTarget.hidden=true;const label=e.currentTarget.nextElementSibling;if(label)label.textContent='预览已失效'}}/>:null}<small>{s.preview?'本机页面预览':'暂无预览'}</small></div>
 <div className="favorite-site-text"><h3>{s.name} <span>↗</span></h3><p>{s.description||'个人收藏'}</p><small>{s.url?new URL(s.url).hostname:'网址待确认'}</small></div></button><div className="favorite-site-actions">{s.preview&&<button disabled={busy} onClick={()=>void change({type:'removePreview',id:s.id})}>移除预览</button>}<button disabled={busy} onClick={()=>{if(confirm('从收藏中移除「'+s.name+'」？'))void change({type:'remove',id:s.id})}}>移除收藏</button></div></article>)}
 {!sites.length&&<p>还没有网站。点击“收藏网站”添加。</p>}</div>{more&&<button aria-label="向右查看更多网站" className="favorite-more" onClick={()=>row.current?.scrollBy({left:360,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><i className="favorite-particles" aria-hidden="true"><b/><b/><b/><b/></i><span>›</span><small>更多</small></button>}</div></>}
 <footer>● 登录状态默认保存在本机 · 网站会话到期仍需登录 <span>文件夹右键可编辑名称与贴纸</span></footer></div></>}
 {notice&&<div className="favorite-notice" role="status">{notice}<button onClick={()=>{onFolder(lastFolder);N('')}}>进入文件夹</button><button onClick={()=>N('')}>×</button></div>}
 {error&&!(bookmark||edit||lastFolder==='manual')&&<div role="alert">{error}</div>}
 {(bookmark||lastFolder==='manual')&&<div className="favorite-overlay"><section className="favorite-dialog" role="dialog" aria-modal="true" aria-label="收藏网站"><h3>收藏网站</h3><label>名称<input autoFocus maxLength={120} value={name} onChange={e=>SN(e.target.value)}/></label><label>网址<input value={url} onChange={e=>SU(e.target.value)}/></label><label>收藏到<select value={dest} onChange={e=>SD(e.target.value)}>{data?.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button onClick={()=>SE({name:'',sticker:'✦'})}>＋ 新建文件夹</button><label className="favorite-check"><input type="checkbox" checked={capture} disabled={!bookmark?.guestId} onChange={e=>SC(e.target.checked)}/>保存当前页面预览（可含私密内容，仅本机存储）</label><p role="alert">{error}</p><div className="favorite-dialog-actions"><button disabled={busy} onClick={()=>{onCloseBookmark();L('')}}>取消</button><button disabled={busy} onClick={async()=>{if(await change({type:'save',folderId:dest,name,url,guestId:bookmark?.guestId,capture})){L(dest);onCloseBookmark()}}}>{busy?'保存中…':'收藏'}</button></div></section></div>}
 {edit&&<div className="favorite-overlay"><section className="favorite-dialog" role="dialog" aria-modal="true" aria-label="自定义文件夹"><h3>{edit.id?'编辑文件夹':'新建文件夹'}</h3><label>名称<input autoFocus maxLength={40} value={edit.name} onChange={e=>SE({...edit,name:e.target.value})}/></label><div className="favorite-stickers">{STICKERS.map(t=><button aria-label={'贴纸 '+t} className={edit.sticker===t?'active':''} key={t} onClick={()=>SE({...edit,sticker:t})}>{t}</button>)}</div><p role="alert">{error}</p><div className="favorite-dialog-actions"><button disabled={busy} onClick={()=>SE(null)}>取消</button><button disabled={busy} onClick={async()=>{B(true);E('');try{const r=await window.api.browser.change({type:'folder',...edit});setData(r.data);SD(edit.id||r.data.folders.at(-1)!.id);SE(null)}catch(e){E(String(e))}finally{B(false)}}}>保存文件夹</button></div></section></div>}
 </div>
}
