import {test} from 'node:test'
import assert from 'node:assert/strict'
import {captureBoundedFrame} from './livePageCapture.ts'
function jpeg(w:number,h:number,bytes=32):string{const b=Buffer.alloc(bytes);Buffer.from([255,216,255,192,0,17,8,h>>8,h&255,w>>8,w&255,3,1,17,0,2,17,0,3,17,0,255,217]).copy(b);return b.toString('base64')}
function fixture(images:string[],attached=false){const calls:{method:string;params?:any}[]=[];let detach=0;const dbg={isAttached:()=>attached,attach:()=>{attached=true},detach:()=>{attached=false;detach++},sendCommand:async(method:string,params?:any)=>{calls.push({method,params});return method==='Page.getLayoutMetrics'?{cssLayoutViewport:{clientWidth:3000,clientHeight:2000,pageX:0,pageY:0},layoutViewport:{clientWidth:6000,clientHeight:4000}}:{data:images.shift()}}};return {dbg,calls,detached:()=>detach}}
test('actual HiDPI pixels capped without nativeImage synchronous encoding',async()=>{const f=fixture([jpeg(3672,2448)]);const r=await captureBoundedFrame(f.dbg,()=>true);assert.ok(r.frame);assert.equal(f.calls[1].params.clip.scale,Math.sqrt(8_990_000/24_000_000));assert.equal(f.detached(),1)})
test('oversized bytes trigger bounded quality fallback',async()=>{const f=fixture([jpeg(4096,2731,8_000_001),jpeg(3672,2448)]);const r=await captureBoundedFrame(f.dbg,()=>true);assert.ok(r.notice);assert.equal(f.calls.length,3);assert.equal(f.calls[2].params.quality,75)})
test('oversized actual pixels rejected even if metrics claimed they fit',async()=>{const f=fixture([jpeg(6000,4000),jpeg(6000,4000),jpeg(6000,4000)]);const r=await captureBoundedFrame(f.dbg,()=>true);assert.equal(r.frame,undefined);assert.ok(r.notice);assert.equal(f.calls.length,4)})
test('foreign debugger never detached',async()=>{const f=fixture([],true);const r=await captureBoundedFrame(f.dbg,()=>true);assert.ok(r.notice);assert.equal(f.calls.length,0);assert.equal(f.detached(),0)})
test('hidden/closed capture drops result and detaches own debugger',async()=>{const f=fixture([jpeg(1000,600)]);let checks=0;const r=await captureBoundedFrame(f.dbg,()=>++checks<3);assert.equal(r.frame,undefined);assert.equal(f.detached(),1)})
test('capture error produces explicit safe notice',async()=>{const f=fixture([]);f.dbg.sendCommand=async()=>{throw Error('secret arbitrary page error')};const r=await captureBoundedFrame(f.dbg,()=>true);assert.ok(r.notice);assert.ok(!r.notice?.includes('secret'));assert.equal(f.detached(),1)})
test('byte and pixel exhaustion returns a visible notice, not stale success',async()=>{const f=fixture([jpeg(4096,4096,8_000_001),jpeg(4096,4096,8_000_001),jpeg(2048,2048,8_000_001)]);const r=await captureBoundedFrame(f.dbg,()=>true);assert.ok(r.notice?.includes('超过'));assert.equal(r.frame,undefined);assert.equal(f.calls.length,4)})
test('external detach then replacement does not detach the new debugger',async()=>{const f=fixture([jpeg(1000,600)]);let listener=()=>{};const dbg={...f.dbg,on:(_event:string,fn:()=>void)=>{listener=fn},removeListener:()=>{},sendCommand:async(method:string,params?:any)=>{const r=await f.dbg.sendCommand(method,params);if(method==='Page.captureScreenshot')listener();return r}};await captureBoundedFrame(dbg,()=>true);assert.equal(f.detached(),0)})
test('malformed JPEG never becomes a frame',async()=>{const f=fixture(['////','bad','']);assert.equal((await captureBoundedFrame(f.dbg,()=>true)).frame,undefined)})
test('timeout detaches owned debugger and consumes late rejection',async()=>{let rejectLate:(e:Error)=>void=()=>{};const f=fixture([]);f.dbg.sendCommand=()=>new Promise((_,reject)=>{rejectLate=reject});const keepAlive=setInterval(()=>{},5000);try{const r=await captureBoundedFrame(f.dbg,()=>true);assert.ok(r.notice?.includes('暂不可用'));assert.equal(f.detached(),1);rejectLate(Error('late protocol close'));await new Promise(resolve=>setImmediate(resolve))}finally{clearInterval(keepAlive)}})
